# Data and methods

## Data

To measure the drivers of environmental innovation I rely on the NIC
approach described above, and first introduced by
@furmanUnderstandingDriversNational2000. However, I use a modified
version, taking insights mainly from
@andrijauskieneRedevelopingNationalInnovative2021. Those authors
redevelop the original NIC framework in a broader fashion and apply it
to European countries. However, their framework is only appropriate for
the national and not the sectoral or technology-specific fields. In
particular on environmental technologies, I follow an approach similar
to that of @moroNationalInnovativeCapacity2019. They also use a modified
version of the NIC approach to study the drivers of innovative outputs
in the water sector in the European Union and China. The main difference
with this thesis is that the range of technologies included and the
selected sample.

Empirically, this thesis uses a panel data set of 36 member countries
from OECD from 2000 to 2020. The study focuses on OECD countries due to
the availability of data, and also their comparability in terms of
similar levels of economic development and their adherence to OECD
standards of environmental protection. On the other hand, OECD includes
a diverse set of countries in terms of population, size, technological
specialization, and geographical representation, giving a sample with
enough variation to yield substantive results.

It is worth noting that not all current OECD countries are included in
the sample. Costa Rica and Colombia, now full members of the OECD,
joined the after the dates of interest of this work, in 2020 and 2021
respectively, and are thus excluded from the analysis.

The main dependent variable is the number of green patents per million
inhabitants produced by country. Patents have long been used as a
measure of the output of innovative activity. One of the first to point
out the advanges of working with patents was
@grilichesPatentStatisticsEconomic1990, who mentions that "they are
available; they are by definition related to inventiveness, and they are
based on what appears to be an objective and only slowly changing
standard". Another advantage pointed out by
@hascicMeasuringEnvironmentalInnovation2015 is their comparability,
which make them specially suited for cross-country comparisons like the
one carried out in this thesis.

That does not mean that patents come without drawbacks. For instance,
patents do not cover the full spectrum of the innovative output; they
mostly do not capture process innovation, and social innovation, for
instance. Another drawback is that patents do not account for the
quality of inventions or their diffusion. Indeed, it is known that the
economic value of patents is very skewed, with a few of them worth a
lot; and most of them with very low economic value
[@hascicMeasuringEnvironmentalInnovation2015].

Nonetheless, for the moment there do not seem to be a better indicator
of output of innovative activity, and therefore I rely on the data
provided by the green patent database of the OECD to build the dependent
variable. The count includes four main categories of technologies, i.e.
environmental management, climate change mitigation, climate change
adaptation, and sustainable ocean economy.

The first independent variable is the common innovation infrastructure.
To measure it I use, I use a set of indicators, including innovation
inputs such as Global Investment in R&D (GERD); R&D personnel; and
investment in higher education. To capture the links between different
actors, I also include the share GERD performed by higher education
institutions and the share of BERD financed by the business sector.
Those factors should give an indication of the general strength of a
country's national innovation system. According to the theoretical
framework, I would expect a mixed effect of this variable on
environmental innovation since the absorptive capacities of are needed
for environmental innovation, but also the path-dependence and lock-in
generated by an innovation system developed on "dirty" technologies
might empower the incumbent stakeholders and hinder the development of
new-to-the-world environmental technologies.

The second dependent variable, environmental policy, includes four main
indicators: the Environmental Policy Stringency Index (EPSI); the green
taxes (as percentage of total tax revenue); the environmental R&D as a
percentage of total R&D expenditure; and the stock of green patents,
which captures the country's specialization in this technological niche.
The first three indicators capture the efforts by public authorities to
create the incentives required by firms to engage in innovation in
environmental technologies, and therefore, I expect them to contribute
positively to national green innovative capacity. The last indicator,
even if not a direct measure of an environmental policy *per se*, indirectly measures the conditions that a country has generated to promote or hinder environmental innovation. Therefore, I would also expect a positive coeficient from this indicator.

Finally, to asses the legal and political environment I use the World
Bank Governance Indicators, in particular quality of regulation and
perception of corruption. These indicators capture the legal, social and
political conditions that form the "environment" in which the green
innovation system has to function. I expect low corruption to be
positively associated to green national innovative capacity, since it
implies that public officials are less prone to be pressured by the
incumbent firms to maintain the status quo; and could engage in bolder
policies to support the environmental transition. I also expect better
regulation to be associated positively to green national innovative
capacity given the previous literature on the topic
[@zangDoesGovernanceEfficiency2019] and the fact that policy, including
environmental policy, requires a strong Government to enforce them. Weak
public sectors can lead to low-quality regulations that are not
well-designed and therefore become ineffective, or simply there might
not be in place adequate mechanisms for enforcement.

Table **XX** shows the full list of variables with their respective
operational definition and source.


## The model

The econometric model used in this study is a panel data fixed effects
model. This model accounts for both within-country and between-country
variation and controls for unobserved heterogeneity. The model is
specified as follows:

$$ 
GreenPatents_{it} = \beta_0 + \beta_1 NII_{it} + 
\beta_2 EP_{it} +
\beta_3 LPF_{it} + \alpha_i + \epsilon_{it}
$$ 

In this equation, the subscript "it" denotes the observation for country
"i" at time "t", and the variables are defined as follows:

-   GreenPatents: the number of green patents granted in country "i" at
    time "t"

-   NII: a measure of the quality of a
    country's innovation infrastructure

-   EP: a measure of a country's environmental policies

-   LPP: a measure of a country's legal and
    political factors affecting innovation and environmental protection

-   $\alpha_i$: a fixed effect capturing unobserved country-specific
heterogeneity

-   $\epsilon_{it}$: the error term for country "i" at time "t"
