# Discussion and Conclusions {-}

The environmental transition is probably the most taxing challenge that humanity has faced. Addressing it requires the coordinated efforts of all countries, regions, and cities. It involves radically transforming a globalized system of production and consumption in a matter of a few decades. Achieving that goal requires to overcome a series of obstacles, including collective action problems, political negligence and powerful lobbies. Technology development is probably not at the top of that priority list. But at the same time, it holds enormous potential to facilitate the transition, and to avoid the worst effects of climate change and loss of biodiversity.

This thesis has presented a framework to understand the main drivers of the green national innovative capacity. It has shown that the evolutionary approach to innovation can be fruitfully applied to environmental innovation, including through an adaptation of classical concepts in the evolutionary economics of innovation, like the National and Sectoral Innovation Systems. Further, it has showed that the empirical framework provided by the National Innovative Capacity can also be adapted to investigate the Green National Innovative Capacity, i.e. the drivers of environmental innovation within the boundaries of National Systems of Innovation.

The main premise of this work has been that a combination of policies in different areas is required to foster innovation in environmental technologies. To that effect, a systemic approach able to incorporate different sources of institutional constraint and their interactions is required. However, most of the literature on the economics of environmental innovation focus on the effect only of environmental policy instruments on innovation. In sight of that, this thesis adds to previous literature by including a broad series of variables in three different but related domains: sectoral (environmental) policyìies; common innovation infrastructure; and quality of governance.

Empirically, this thesis relied on an original panel dataset for 36 OECD countries over two decades, built from various OECD and World Bank data sources. The dataset included information on eleven indicators along the three previously mentioned dimension. To measure the output of innovative activity, it used the number of patents in environmental technologies produced in each relevant country during the study period.

The results from the econometric analysis suggest that both a strong National Innovation System in the form of common innovation infrastructure, and targetted sectoral policies (stringent environmental policy and green R&D support) are drivers of environmental innovation. The quality of the governance environment was not found to be significant for explaining the dependent variable; however, that might be due to an inadequacy of the chosen indicator. Adding a layer of complexity, the analysis also suggest that investment in R&D has a very strong positive effect on environmental innovation; while other institutions within the National Innovation System -in particular the relative participation of the business sector in the innovative endeavor- might actually hinder innovation in environmental technologies. This does not come a surprise; in the theoretical framework it was discussed how institutions generate regularities that create path dependencies and lock-ins; and that it is the role of policy to break those lock-ins when they result in a decrease of social welfare.

Those results are meant to be taken as exploratory, as more research is needed into which specific instruments -an combinations of instruments- are more suitable to promote environmental innovation. It is also possible that different contexts call for different policy mixes. Therefore the aforementioned analysis should not be taken as a “recipe”.

A more general conclusion from this research is that innovation in general and especially the radical green innovation needed for the environmental transition does not emerge from a vacuum. Instead, it requires the active involvement of different stakeholders of the innovation process: businesses, consumers, and Governments. It also demands to carefully craft the institutional frameworks in which those actors will interact, as part of what some research calls “Transition Management” or “Strategic Niche management” (SNM). Those approaches avoid the linearity of some interventions and instead take a systemic approach in dealing with the transition.

# Limitations {-}

In an exercise of academic honesty, it is relevant to acknowledge the limitations of the present work and suggest paths for future research to explore.

In terms of the theoretical framework, it is missed a more robust corpus of literature dealing specifically with environmental innovation from an evolutionary perspective. Even if there is a growing interest, still most of the environmental innovation literature stems from neoclassical perspectives.

Specifically on the decisions and approaches taken in this thesis, the exclusion of China becomes a major limitation. China has become the world leader in patenting and failing to include it in the analysis means leaving out a big part of the process that it intends to understand. A more comprehensive sample that includes also other major patenting countries like Russia and India would be a welcome addition to this work.

On the methods, it is worth noting that the traditional econometric techniques, like the ones used in this work, have many advantages like the simplicity and parsimony; but also some drawbacks. For instance, they are not best suited to deal with complexity. Complementing the ‘traditional’ econometric analysis with other techniques, like ABM or QCA, could provide new insights and open new avenues of inquiry.
